Robocopy.exe D:\0721 X:\0721 /MIR
Robocopy.exe D:\c# X:\c# /MIR
Robocopy.exe D:\doc X:\doc /MIR
Robocopy.exe D:\doc_old X:\doc_old /MIR
Robocopy.exe D:\Downloads X:\Downloads /MIR
Robocopy.exe D:\java X:\java /MIR
Robocopy.exe D:\manga X:\manga /MIR
Robocopy.exe D:\office X:\off:ice /MIR
Robocopy.exe D:\doc D:\Dropbox\Dropbox\doc   /MIR
Robocopy.exe D:\manga D:\Dropbox\Dropbox\manga   /MIR
Robocopy.exe D:\office D:\Dropbox\Dropbox\office  /MIR
Robocopy.exe  F:\ChilkatDotNet4-9.4.1-win32\ X:\ChilkatDotNet4-9.4.1-win32\ /MIR
Robocopy.exe F:\dlsite\ X:\dlsite\ /MIR
Robocopy.exe F:\DotNetZipLib-Runtime-v1.9\ X:\DotNetZipLib-Runtime-v1.9\ /MIR
Robocopy.exe F:\Ed\ X:\Ed\ /MIR
Robocopy.exe F:\EvernoteBackup\ X:\EvernoteBackup\ /MIR
Robocopy.exe F:\EvernoteEnex\ X:\EvernoteEnex\ /MIR
Robocopy.exe F:\mymusic\ X:\mymusic\ /MIR
Robocopy.exe F:\pic_INTER\ X:\pic_INTER\ /MIR
Robocopy.exe F:\pic_SD\ X:\pic_SD\ /MIR
Robocopy.exe F:\ダウンロード\ X:\ダウンロード\ /MIR
