option batch on
open takehiko@t100ta
synchronize remote -delete D:\0721 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/0721
synchronize remote -delete  D:\c# 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/c#
synchronize remote -delete  D:\doc 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/doc
synchronize remote -delete  D:\Downloads /media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/Downloads
synchronize remote -delete  D:\java 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/java
synchronize remote -delete  D:\manga 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/manga
synchronize remote -delete  D:\office 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/office
synchronize remote -delete  D:\webGL 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/webGL


synchronize remote -delete  F:\dlsite 		/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/dlsite
synchronize remote -delete  F:\EvernoteBackup 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/EvernoteBackup
synchronize remote -delete  F:\EvernoteEnex 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/EvernoteEnex
synchronize remote -delete  F:\mymusic 		/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/mymusic
synchronize remote -delete  F:\pic_INTER 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/pic_INTER
synchronize remote -delete  F:\pic_SD		 /media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/pic_SD
synchronize remote -delete  F:\ダウンロード 	/media/takehiko/1b809b77-67f0-432f-947b-78ab406976d0/home/ダウンロード

exit
